# Generated by Django 5.0.5 on 2024-11-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_shop_alter_product_image_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/default_product.png', null=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
