# Generated by Django 5.1.2 on 2024-12-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_categoty_product_brand_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
    ]
