# Generated by Django 5.0.5 on 2024-11-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_orderhistory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomehistory',
            name='price_at_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='soldhistory',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
