# Generated by Django 5.0.5 on 2024-11-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_income_remove_incomehistory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='profit',
            field=models.FloatField(null=True),
        ),
    ]
