# Generated by Django 5.0.5 on 2024-11-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_orderhistory_profit'),
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shop'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shop'),
        ),
    ]
