# Generated by Django 5.1.2 on 2024-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_incomehistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomehistory',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
