# Generated by Django 5.1.2 on 2024-12-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_incomehistory_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomehistory',
            name='change',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
